toolTips = [
    "Different Flowers have different grow times",
    "Different Flowers have different drought tolerances",
    "Different Flowers produce different pollen colors",
    "Wilting Flowers means they need more water",
    "Flowers need water while they are growing",
    "Flowers only produce pollen for one Hive per day",
    "Hives have diminishing returns on increasing number of Flowers",
    "Partial Honey produced by Hives is saved",
    "Weeds reduce Honey production",
    "There are four colors of Honey: yellow, blue, purple, and pink",
    "Try planting a lot of the same type of Flowers around a Hive",
    "Hives collect pollen from Flowers within two plots",
    "Sprinklers water surrounding Flowers every morning",
    "Running your Sprinklers every day can be expensive",
    "Water costs money! Make sure to save enough for your Flowers",
    "Clearing out Brambles gives you more room to plant in",
    "Brambles can be cleared by using the Clippers",
    "You can buy more Clippers in Toad Leckman’s Shop",
    "Your get more bees for each Hive in your garden",
    "The landscape will improve as you restore the land",
    "You can hold all seeds of a single type at once",
    "Press B while holding something to put it in your backpack",
    "Navigate the tabs of your backpack to see what you have",
    "Your Honey stock and supplies are all in your backpack",
    "Toad Leckman’s Shop has a limited stock that refills each day",
    "There’s more than just Flowers at Toad Leckman’s Shop",
    "Navigate Toad Leckman’s Shop’s tabs to see what's on offer"
    
];